import type { Metadata } from 'next';
import Script from 'next/script';
import { Inter } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="Cookiebot"
          src="https://consent.cookiebot.com/uc.js"
          data-cbid="6a512edd-f989-41d9-92eb-39bc0c620286"
          data-blockingmode="auto"
          type="text/javascript"
        ></Script>
      </head>
      <body className={cn(inter.className, 'antialiased min-h-screen')}>
        {children}
      </body>
    </html>
  );
}
